require_relative "commands/basic_command"
require_relative "commands/add_command"
require_relative "commands/subtract_command"
require_relative "commands/multiply_command"
require_relative "commands/divide_command"
require_relative "commands/cancel_command"